<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="laptop" ignored="0" name="Default test" tests="14" failures="2" timestamp="20 Aug 2018 03:43:31 GMT" time="84.186" errors="0">
  <testcase name="test1_InvalidEmailForm" time="1.755" classname="testclasses.TestNG_SignUp"/>
  <testcase name="test1_InvalidEmailForm" time="2.624" classname="testclasses.TestNG_SignUp"/>
  <testcase name="test1_InvalidEmailForm" time="1.027" classname="testclasses.TestNG_SignUp"/>
  <testcase name="test1_InvalidEmailForm" time="1.079" classname="testclasses.TestNG_SignUp"/>
  <testcase name="test1_InvalidEmailForm" time="1.078" classname="testclasses.TestNG_SignUp"/>
  <testcase name="test2_ZipOutOfRange" time="2.406" classname="testclasses.TestNG_SignUp"/>
  <testcase name="test3_ZipInRange" time="4.615" classname="testclasses.TestNG_SignUp"/>
  <testcase name="test4_InvalidRegisterForm" time="9.574" classname="testclasses.TestNG_SignUp"/>
  <testcase name="test4_InvalidRegisterForm" time="2.516" classname="testclasses.TestNG_SignUp"/>
  <testcase name="test4_InvalidRegisterForm" time="2.17" classname="testclasses.TestNG_SignUp"/>
  <testcase name="test4_InvalidRegisterForm" time="2.112" classname="testclasses.TestNG_SignUp"/>
  <testcase name="test4_InvalidRegisterForm" time="2.571" classname="testclasses.TestNG_SignUp"/>
  <testcase name="test4_InvalidRegisterForm" time="2.254" classname="testclasses.TestNG_SignUp">
    <failure type="java.lang.AssertionError" message="expected [Your card number is incomplete.] but found [Password should be 6 characters or more]">
      <![CDATA[java.lang.AssertionError: expected [Your card number is incomplete.] but found [Password should be 6 characters or more]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at testclasses.TestNG_SignUp.test4_InvalidRegisterForm(TestNG_SignUp.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test4_InvalidRegisterForm -->
  <testcase name="test4_InvalidRegisterForm" time="2.774" classname="testclasses.TestNG_SignUp">
    <failure type="java.lang.AssertionError" message="expected [Your card number is invalid.] but found [Password should be 6 characters or more]">
      <![CDATA[java.lang.AssertionError: expected [Your card number is invalid.] but found [Password should be 6 characters or more]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at testclasses.TestNG_SignUp.test4_InvalidRegisterForm(TestNG_SignUp.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test4_InvalidRegisterForm -->
</testsuite> <!-- Default test -->
